
import NavBar from "./NavBar";
import SideBar from "./SideBar";

import "./globals.css";


export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <NavBar />
        <div className="flex">
          <div className="w-[15%]">
            <SideBar/>
          </div>
          <div className="w-[85%]">{children}</div>
        </div>
      </body>
    </html>
  );
}
